if vim.g.vscode then
  require "user.comment"
  require "user.surround"
  require "user.leap"
else
  require "user.leap"
  require "user.surround"
  require "user.options"
  require "user.keymaps"
  require "user.plugins"
  require "user.colorscheme"
  require "user.cmp"
  require "user.lsp"
  require "user.telescope"
  require "user.gitsigns"
  require "user.treesitter"
  require "user.autopairs"
  require "user.comment"
  require "user.nvim-tree"
  require "user.bufferline"
  require "user.lualine"
  require "user.toggleterm"
  require "user.project"
  require "user.impatient"
  require "user.indentline"
  require "user.alpha"
  require "user.whichkey"
  require "user.autocommands"
end
